# Generated by Django 3.2.25 on 2024-08-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('salary', models.FloatField()),
                ('email', models.EmailField(max_length=30)),
                ('mobile', models.CharField(max_length=13, unique=True)),
            ],
        ),
    ]
